# -*- encoding: utf-8 -*-
'''
@File    :   __init__.py
@Time    :   2024/06/10 11:22:40
@Author  :   ztf 
@Contact :   tengfeizhang@whu.edu.cn
@License :   (C)Copyright 2024, Wuhan University
@Desc    :   None
'''

import torch
import itertools
import torch.nn.functional as F
from src.model.common import *
from .base_model import BaseModel
from src.loss import Loss
from src.utils.image_pool import ImagePool


class CinCGAN(BaseModel):
    def __init__(self, args) -> None:
        # Generator
        super(CinCGAN,self).__init__(args)
        self.args = args

        if self.isTrain:
            self.model_names = ['G1', 'G2','G3', 'D1', 'D2', 'SR']
            # Discriminator
            self.D1 = Discriminator(in_channels=args.n_channels, out_channels=args.n_channels, h_stride=1, bias=True).to(0)
            self.D2 = Discriminator(in_channels=args.n_channels,
                                out_channels=args.n_channels, h_stride=2, bias=True).to(0)
        else:
            self.model_names = ['G1', 'G2', 'G3', 'SR']
                                        
        self.G1 = ResGenerator(in_channels=args.n_channels,
                               out_channels=args.n_channels, kernel_size=3, stride=1,  bias=True).to(0)
        self.G2 = ResGenerator(in_channels=args.n_channels,
                               out_channels=args.n_channels, kernel_size=3, stride=1, bias=True).to(0)
        self.G3 = ResGenerator(in_channels=args.n_channels,
                               out_channels=args.n_channels, kernel_size=4, stride = args.scale, bias=True).to(0)
        # SR network
        self.SR = EDSR_net(scale=args.scale).to(0)
        # self.SR = SRCNN(args.scale).to(0)
        self.initialization(args)

    def set_input(self, lr : torch.Tensor , hr : torch.Tensor) -> None:
        self.hr = hr
        self.hr_b = F.interpolate(hr.float(), scale_factor=1/self.args.scale, mode="bicubic")
        self.x = lr

    def forward_lr(self) -> None:
        """ forward process of CinCGAN.
        """
        # get x of target domain
        # inner cycle
        self.fake_lr = self.G1(self.x)
        self.real_lr = self.G1(self.hr_b)
        self.lr_cyc = self.G2(self.fake_lr)
       
    def forward(self) -> None:
         # outer cycle
        self.fake_hr = self.SR(self.G1(self.x))  # calculate tv loss
        self.real_hr = self.SR(self.hr_b) # calculate identity loss
        self.x_cyc = self.G3(self.fake_hr) # calculate cyc loss
        self.output = self.fake_hr
        
    def backward_G_HR(self) -> None:
        """Calculate the loss of generator and update weights
        of generator
        """
        pred_fake = self.D2(self.fake_hr)
        loss_gan = self.loss.l2_loss(pred_fake, torch.ones_like(pred_fake))
        loss_cyc = self.loss.l2_loss(self.x_cyc, self.x, reduction='sum')
        loss_idt = self.loss.l2_loss(self.real_hr, self.hr)
        # loss_tv = self.loss.tv_loss(self.fake_hr)
        self.loss_G = loss_gan + 10*loss_cyc + 5*loss_idt
        self.loss_G.backward()

    def backward_D_basic(self, net_D, real, fake) -> torch.Tensor:
        """Calculate GAN loss for the discriminator

        Parameters:
            netD (network)      -- the discriminator D
            real (tensor array) -- real images
            fake (tensor array) -- images generated by a generator

        Return the discriminator loss.
        We also call loss_D.backward() to calculate the gradients.
        """
        # real
        pred_real = net_D(real)
        loss_D_real = self.loss.l2_loss(pred_real, torch.ones_like(pred_real))
        # fake
        pred_fake = net_D(fake.detach())
        loss_D_fake = self.loss.l2_loss(pred_fake, torch.zeros_like(pred_fake))
        loss_D = loss_D_real + loss_D_fake
        loss_D.backward(retain_graph=True)
        return loss_D

    def backward_D_HR(self) -> None:
        """Calculate the loss of discriminator and update weights
        of discriminator D2
        """
        self.loss_D = self.backward_D_basic(self.D2, self.hr, self.fake_hr)
    
    def backward_D_LR(self) -> None:
        """update D1 of step 1
        """
        self.backward_D_basic(self.D1, self.real_lr, self.fake_lr)
    
    def backward_G_LR(self) -> None:
        """update G1 of step 1
        """
        pred_fake = self.D1(self.fake_lr)
        loss_G_LR = 10 * self.loss.l1_loss(self.lr_cyc, self.x) +\
            self.loss.l2_loss(pred_fake, torch.ones_like(pred_fake))
        loss_G_LR.backward(retain_graph=True)

    def optimize_parameters(self) -> None:
        """Calculate losses, gradients, and update network weights;
         called in every training iteration;
         first update discriminator, then update weights of generator
        """
        self.forward_lr()

        self.optimizer_D.zero_grad()
        self.backward_D_LR()
        self.optimizer_D.step()
        # Generator
        self.optimizer_G.zero_grad()
        self.backward_G_LR()
        self.optimizer_G.step()
        
        # Step 2
        self.forward()
        self.optimizer_D.zero_grad()
        self.backward_D_HR()
        self.optimizer_D.step()

        self.optimizer_G.zero_grad()
        self.backward_G_HR()
        self.optimizer_G.step()

    def initialization(self, args) -> None:
        """init optimizers and schedulers
        """
        super(CinCGAN, self).initialization()    
        if self.args.isTrain:
            # self.fake_pool = ImagePool(50)
            self.optimizer_G = torch.optim.Adam(itertools.chain(self.G1.parameters(), self.G2.parameters(), self.SR.parameters(),
                                                                self.G3.parameters()), lr=args.lr, betas=[0.9, args.beta2], eps=args.epsilon)  # type: ignore
            self.optimizer_D = torch.optim.Adam(itertools.chain(self.D1.parameters(), self.D2.parameters()), lr=args.lr, betas=[
                                                0.9, args.beta2], eps=args.epsilon)  # type: ignore
            self.optimizers.append(self.optimizer_G)
            self.optimizers.append(self.optimizer_D)
            self.loss = Loss(args.weight)
            self.loss_G = 0.0
            self.loss_D = 0.0
            self.schedulers = [self.get_scheduler(
                optimizer, args)for optimizer in self.optimizers]
            # load pretrained weight
            self.load_networks(self.SR, args.resume_SR)      
            self.load_networks(self.G1, args.resume_DT + "net_G1.pth")
            self.load_networks(self.G2, args.resume_DT + "net_G2.pth")
            self.load_networks(self.D1, args.resume_DT + "net_D1.pth")
        