# -*- encoding: utf-8 -*-
'''
@File    :   __init__.py
@Time    :   2024/06/10 11:22:40
@Author  :   ztf 
@Contact :   tengfeizhang@whu.edu.cn
@License :   (C)Copyright 2024, Wuhan University
@Desc    :   None
'''

import torch
import itertools
import torch.nn as nn
import torch.nn.functional as F
from .base_model import BaseModel
from src.model.common import *
from src.loss import Loss
from src.utils.image_pool import ImagePool

Tensor = torch.Tensor


class CycleGAN(BaseModel):
    """an image translation before super-resolution
    """

    def __init__(self, args) -> None:
        super().__init__(args)
        if self.isTrain:
            self.model_names = ['G1', 'G2', 'D1', 'D2']
            # Discriminator
            self.D1 = NLayerDiscriminator(in_channels=args.n_channels).to(0)
            self.D2 = NLayerDiscriminator(in_channels=args.n_channels).to(0)

        else:  # during test time, only load Gs
            self.model_names = ['G1', 'G2']
        self.G1 = cResGenerator(in_channels=args.n_channels,
                                out_channels=args.n_channels).to(0)
        self.G2 = cResGenerator(in_channels=args.n_channels,
                                out_channels=args.n_channels).to(0)
        self.initialization(args)

    def set_input(self, lr: Tensor, hr: Tensor) -> None:
        """direction:domain A -> domain B

        Args:
            lr (Tensor): the target domain
            hr (Tensor): the source domain
        """
        self.syn_lr = F.interpolate(
            hr.float(), scale_factor=1/self.args.scale, mode="bicubic")  # A
        self.real_lr = lr  # B

    def forward(self) -> None:
        """Run forward pass; called by both functions <optimize_parameters> and <test>.
        """
        self.fake_lr = self.G1(self.syn_lr)     # G_A(A)
        self.rec_syn = self.G2(self.fake_lr)    # G_B(G_A(A))
        self.fake_syn = self.G2(self.real_lr)   # G_B(B)
        self.rec_real = self.G1(self.fake_syn)  # G_A(G_B(B))

    def backward_D_basic(self, net_D, real, fake) -> torch.Tensor:
        """Calculate GAN loss for the discriminator

        Parameters:
            netD (network)      -- the discriminator D
            real (tensor array) -- real images
            fake (tensor array) -- images generated by a generator

        Return the discriminator loss.
        We also call loss_D.backward() to calculate the gradients.
        """
        # real
        pred_real = net_D(real)
        loss_D_real = self.loss.l2_loss(pred_real, torch.ones_like(pred_real))
        # fake
        pred_fake = net_D(fake.detach())
        loss_D_fake = self.loss.l2_loss(pred_fake, torch.zeros_like(pred_fake))
        loss_D = (loss_D_real + loss_D_fake) * 0.5
        loss_D.backward()
        return loss_D

    def backward_D_A(self) -> None:
        """Calculate GAN loss for discriminator D_A"""
        fake_lr = self.fake_pool_lr.query(self.fake_lr)  # fake_A

        self.loss_D_real = self.backward_D_basic(
            self.D1, self.real_lr, fake_lr)

    def backward_D_B(self) -> None:
        """Calculate GAN loss for discriminator D_B"""
        fake_syn = self.fake_pool_syn.query(self.fake_syn)  # fake_B
        self.loss_D_syn = self.backward_D_basic(self.D2, self.syn_lr, fake_syn)
        self.loss_D = self.loss_D_syn + self.loss_D_real

    def backward_G(self) -> None:
        # GAN loss D_A(G_A(A))
        pred_fake_B = self.D1(self.fake_lr)
        loss_G_A = self.loss.l2_loss(pred_fake_B, torch.ones_like(pred_fake_B))
        # GAN loss D_B(G_B(B))
        pred_fake_A = self.D2(self.fake_syn)
        loss_G_B = self.loss.l2_loss(pred_fake_A, torch.ones_like(pred_fake_A))
        # Forward cycle loss || G_B(G_A(A)) - A||
        loss_cyc_A = self.loss.l1_loss(self.rec_syn, self.syn_lr) * 10
        # Backward cycle loss || G_A(G_B(B)) - B||
        loss_cyc_B = self.loss.l1_loss(self.rec_real, self.real_lr) * 10
        self.loss_G = loss_cyc_A + loss_cyc_B + loss_G_A + loss_G_B
        self.loss_G.backward()

    def optimize_parameters(self) -> None:
        """Calculate losses, gradients, and update network weights;
         called in every training iteration;
         first update discriminator, then update weights of generator
        """
        self.forward()
        # G_A and G_B
        self.set_requires_grad([self.D1, self.D2], False)
        self.optimizer_G.zero_grad()  # set G_A and G_B's gradients to zero
        self.backward_G()             # calculate gradients for G_A and G_B
        self.optimizer_G.step()       # update G_A and G_B's weights
        # D_A and D_B
        self.set_requires_grad([self.D1, self.D2], True)
        self.optimizer_D.zero_grad()   # set D_A and D_B's gradients to zero
        self.backward_D_A()      # calculate gradients for D_A
        self.backward_D_B()      # calculate gradients for D_B
        self.optimizer_D.step()  # update D_A and D_B's weights

    def initialization(self, args) -> None:
        """init optimizers and schedulers
        """
        super().initialization()
        if self.args.isTrain:
            self.fake_pool_lr = ImagePool(50)
            self.fake_pool_syn = ImagePool(50)
            self.optimizer_G = torch.optim.Adam(itertools.chain(self.G1.parameters(),
                                                                self.G2.parameters()), lr=args.lr, betas=[args.beta1, args.beta2], eps=args.epsilon)  # type: ignore
            self.optimizer_D = torch.optim.Adam(itertools.chain(self.D1.parameters(), self.D2.parameters()), lr=args.lr, betas=[
                                                args.beta1, args.beta2], eps=args.epsilon)  # type: ignore
            self.optimizers.append(self.optimizer_G)
            self.optimizers.append(self.optimizer_D)
            self.loss = Loss(args.weight)
            self.loss_G = 0.0
            self.loss_D = 0.0
            self.schedulers = [self.get_scheduler(
                optimizer, args)for optimizer in self.optimizers]
